/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SHIVA_LINGA.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Shiva(props) {
  const { nodes, materials } = useGLTF('/models/SHIVA_LINGA.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={298.184} near={152.873} fov={39.598} position={[-119.973, 89.547, 204.054]} rotation={[-0.289, -0.46, -0.131]} />
      <group position={[-645.473, 0, -31.798]}>
        <mesh geometry={nodes.Object_0_0.geometry} material={materials['White Ceramic #1']} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['White Ceramic #2']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SHIVA_LINGA.glb')
